controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth
    methods: ['POST']

tweets:
    path: /api/tweets
    controller: App\Controller\TweeterController::getTweets
    methods: GET